cidb and cidb-scan: linting and better help
Cleanup some comments made by the ever great shellcheck. Add some more
info the help text displayed.

diff --git a/bin/cidb b/bin/cidb
--- a/bin/cidb
+++ b/bin/cidb
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 #vim: sw=2 ts=2 sts=2:
-
 set -e -o pipefail
-progname="$(basename $0)"
 
-# Add the bin to the PATH, first, for finding cidb-* commands
-# Makes it work inside a bundle or called direct in checkout (./bin/cidb) when
-# not added to the PATH.
-DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd )"
+# Add the cidb bin to the PATH, first, for finding cidb-* commands.  Makes it
+# work inside a bundle or called direct in checkout (./bin/cidb) when not added
+# to the PATH.
+DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd )
 PATH="$DIR:$PATH"
+
+progname="$(basename "$0")"
 
 usage() {
 cat <<EOHELP
@@ -16,47 +16,65 @@ USAGE:
   $progname [COMMAND] [OPTIONS]
 
 OPTIONS:
-  -h       Show this help"
+  -h  Show this help
 
 DESCRIPTION:
-
-CIDB (Continuous Investigation DataBase), is a companion tool to run with
-whatever you do for CI. You tell it when you start and when your done. Like a
-crime scene investigation, it hovers up logs, junit files, images etc,
-recording all the details in a database and the artifacts in storage.
+  CIDB (Continuous Integration DataBase), is a companion tool to run with whatever
+you do for CI. You tell it when you start and when your done. Like a crime scene
+investigation, it hovers up logs, junit files, images etc, recording all the
+details in a database and the artifacts in storage.
 
 This top level command provides help and dispatch to more specific commands.
 
 COMMANDS:
+  These are the main user commands and make up the public interface:
+
+  setup - setup database
   scan  - run in a build site to collect data
   list  - list data collected from builds
+
+(Others exist and get called by internally, they should be considered private
+for now - feel free to use but they might change, go away in future!).
+
+EXAMPLE:
+
+  export CIDB_DATABASE_URL=sqlite://ci.db
+  cidb setup
+  make test
+  cidb scan .
+  cidb list
+  cidb list builds
+
+EXIT CODES:
+  If the COMMAND is found and run, exits with that commands status. Otherwise:
+
+   0  - when showing usage
+   1  - unknown option or opt parsing error
+   2  - sub cidb COMMAND not found
+
 EOHELP
   exit 0
 }
 
 while getopts ":h" opt; do
   case ${opt} in
-    h ) usage
-      ;;
-    \? ) usage
+    h ) usage ;;
+    * ) echo "$progname: fatal: unknown option: $opt"
+      exit 1
       ;;
   esac
 done
 shift $((OPTIND -1))
 
-if [ $# -eq 0 ]; then
+if [ $# -eq 0 ]; then # no args
   usage
 fi
 
-# alias cidb-ls='cidb-list'
-# cidb-ls() {
-#   cidb-list "$@"
-# }
-
-cmd="cidb-$1"; shift
-if which "$cmd" &>/dev/null; then
-  exec $cmd "$@"
+# If we have an arg, it is a sub-command. Dispatch to (exec) the command if
+# found, fail otherwise.
+cmd="$1"; shift
+if command -v "cidb-$cmd" &>/dev/null; then
+  exec "cidb-$cmd" "$@"
 fi
-
-echo "$progname: error: unknown command $cmd"
+echo "$progname: fatal: unknown command: $cmd"
 exit 2
diff --git a/bin/cidb-scan b/bin/cidb-scan
--- a/bin/cidb-scan
+++ b/bin/cidb-scan
@@ -8,8 +8,18 @@ info() {
   echo "$progname: info: $*"
 }
 
-log-error() {
-  echo "$progname: error: $*"
+# Log message as fatal and exit 10.
+#   fatal "Boom"
+# If the first arg is a number, use that exit code.
+#   fatal 23 Not enough entropy
+fatal() {
+  code=10
+  if [ "$1" -eq "$1" ] 2>/dev/null; then # is number
+    code="$1"
+    shift
+  fi
+  echo "$progname: fatal: $*"
+  exit "$code"
 }
 
 export CIDB_BUILD_ID
@@ -48,6 +58,9 @@ while getopts ":hfb:" opt; do
       ;;
     \? ) usage
       ;;
+    * )
+      fatal "Unknown option: ${opt}"
+      ;;
   esac
 done
 shift $((OPTIND -1))
@@ -75,9 +88,8 @@ scan() {
 
   scan-builder
   if [[ -z "$CIDB_BUILD_ID" ]]; then
-    log-error "CIDB_BUILD_ID not set, can't identify the build"
     cidb-data --put scan.end-time "$(date +%Y-%m-%dT%H:%M:%S%z)"
-    exit 10
+    fatal 10 "CIDB_BUILD_ID not set, can't identify the build"
   fi
   cidb-data --put build.build_id "$CIDB_BUILD_ID"
 
@@ -101,8 +113,7 @@ setup-data() {
       info Removing existing scan with force
       rm -rf "$CIDB_DATA"
     else
-      log-error Directory already scanned. Use force '(-f)' to re-scan.
-      exit 11
+      fatal Directory already scanned. Use force '(-f)' to re-scan.
     fi
   fi
   mkdir -p "$CIDB_DATA"
@@ -119,7 +130,7 @@ scan-builder() {
     CIDB_BUILDER=github
   fi
   cidb-data --put build.builder "$CIDB_BUILDER"
-  info Scanning $CIDB_BUILDER build
+  info Scanning "$CIDB_BUILDER" build
   scan-"$CIDB_BUILDER"
 }
 
